name: "Docker Build"
description: "Build and tag Docker image"
inputs:
  image-name:
    required: true
  registry:
    required: true
  version:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        DOCKER_TAG="${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.version }}"
        echo "DOCKER_TAG=$DOCKER_TAG"
        echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
      shell: bash
