name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: 'Git branch or Tag to deploy'
        required: true
        type: string
        default: 'main'
      environment:
        description: 'Target environment (dev/int/prod)'
        required: true
        type: string
        default: 'dev'

env:
  IMAGE_NAME: app-backend
  REGISTRY: containers.github.azure.cloud
  CONFIG_REPO: bujitsu93/actiune-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get Short commit SHA
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "SHORT_SHA = $SHORT_SHA"

      - name: build image
        run: |
          echo "SHORT_SHA=$SHORT_SHA"
          DOCKER_TAG="${REGISTRY}/${IMAGE_NAME}-${SHORT_SHA}"
          echo "DOCKER_TAG=$DOCKER_TAG"
        env:
          SHORT_SHA: ${{ env.SHORT_SHA }}
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}

      - name: Checkout config repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.CONFIG_REPO }}
          token: ${{ secrets.CONFIG_REPO_PAT }}
          path: config-repo

      - name: Debug file paths
        run: |
          echo "Working dir: $(pwd)"
          ls -R config-repo
          echo "Listing config-repo directory..."

      - name: Show directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Top level:"
          ls -l
          echo "Inside config-repo:"
          ls -l config-repo
          echo "Inside config-repo/config/dev:"
          ls -l config-repo/config/dev
      
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq --version

      - name: Update deployment file
        run: |
          DEPLOY_FILE="config-repo/config/${{ github.event.inputs.environment }}/deployment.yaml"
          echo "DEPLOY_FILE=$DEPLOY_FILE" >> $GITHUB_ENV
          echo "DEPLOY_FILE is $DEPLOY_FILE"

          IMAGE_TAG="${REGISTRY}/${IMAGE_NAME}-${SHORT_SHA}"
          
          echo "Initial IMAGE_TAG is $IMAGE_TAG"

         
          yq e -i ".spec.template.spec.containers[0].image = \"${IMAGE_TAG}\"" "${DEPLOY_FILE}"

          echo "New image value:"
          yq e '.spec.template.spec.containers[0].image' "$DEPLOY_FILE"
        env:
          SHORT_SHA: ${{ env.SHORT_SHA }}
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        