name: deploy prod

on:
  release:
    types: [published]

env:
  IMAGE_NAME: app-backend
  REGISTRY: containers.github.azure.cloud
  CONFIG_REPO: bujitsu93/actiune-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Short commit SHA
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Set version from release tag
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build image
        run: |
          echo "SHORT_SHA=$SHORT_SHA"
          echo "VERSION=$VERSION"
          DOCKER_TAG="${REGISTRY}/${IMAGE_NAME}:${VERSION}"
          echo "DOCKER_TAG=$DOCKER_TAG"
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          VERSION: ${{ env.VERSION }}

      - name: Checkout config repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.CONFIG_REPO }}
          token: ${{ secrets.CONFIG_REPO_PAT }}
          path: config-repo

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq --version

      - name: Update deployment file
        run: |
          DEPLOY_FILE="config-repo/config/prod/deployment.yaml"


          echo "old image value:"
          yq e '.spec.template.spec.containers[0].image' "$DEPLOY_FILE"

          IMAGE_TAG="${REGISTRY}/${IMAGE_NAME}:${VERSION}"
          
          echo "IMAGE_TAG is $IMAGE_TAG"

         
          yq e -i ".spec.template.spec.containers[0].image = \"${IMAGE_TAG}\"" "${DEPLOY_FILE}"

          echo "New image value:"
          yq e '.spec.template.spec.containers[0].image' "$DEPLOY_FILE"

          echo "Full updated deployment.yaml file:"
          cat "${DEPLOY_FILE}"

        env:
          SHORT_SHA: ${{ env.VERSION }}
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        
      - name: Commit and push deployment file
        run: |

          cd config-repo
          
          git config user.name "bujitsu93"
          git config user.email "useful.bujicu@gmail.com"

          git add config/prod/deployment.yaml

          git commit -m "Update deployment image to ${IMAGE_NAME}:${VERSION}" || echo "No changes to commit"

          git push origin main

        env:
          SHORT_SHA: ${{ env.VERSION }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}